In [3]:
from google.colab import drive
drive.mount('/content/gdrive')

Go to this URL in a browser: https://accounts.google.com/o/oauth2/auth?client_id=947318989803-6bn6qk8qdgf4n4g3pfee6491hc0brc4i.apps.googleusercontent.com&redirect_uri=urn%3Aietf%3Awg%3Aoauth%3A2.0%3Aoob&scope=email%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdocs.test%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdrive%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdrive.photos.readonly%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fpeopleapi.readonly&response_type=code

Enter your authorization code:
··········
Mounted at /content/gdrive

In [0]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn import metrics
from sklearn.utils import resample
from sklearn.feature_extraction import FeatureHasher

In [5]:
val_df = pd.read_csv('/content/gdrive/My Drive/we_data/validation.csv')
val_df.head()

,click,weekday,hour,bidid,userid,useragent,IP,region,city,adexchange,...,slotheight,slotvisibility,slotformat,slotprice,creative,bidprice,payprice,keypage,advertiser,usertag
0,0,4,20,bbcb813b6166538503d8b33a5602d7d72f6019dc,663169f66491c98c69f1f94a5c48fa34aa9fe06f,windows_ie,211.144.203.*,79,79,1.0,...,600,2,1,0,cb7c76e7784031272e37af8e7e9b062c,300,23,bebefa5efe83beee17a3d245e7c5085b,1458,"13866,10111"
1,0,1,21,5a07316c49477cb5d9b4d5aa39c27d6c3be7f92d,a23f0cfab6592c137f796e68fa752fceba08bb1b,windows_chrome,58.247.250.*,79,79,1.0,...,90,0,1,0,c938195f9e404b4f38c7e71bf50263e5,238,75,a3becb967c015e9acb5e72f22b100ef8,3476,"10075,10057,10024,10052,10083,10063,10006,10110"
2,0,4,8,f6ece71dae81d6b16bfb24ad6dd5611472d4c673,5105a013ea54a9706146033e6a138d5234a3803e,windows_ie,117.12.111.*,2,2,2.0,...,250,2,0,5,911b2d84826786018761e8c0b0a3a60c,238,65,d29e59bf0f7f8243858b8183f14d4412,3358,"13866,10024,10059,10063,13776,10083,10006,10111"
3,0,5,15,b4d5c57c9b38ff5a12954fa01e11931b4e6bfbbb,577e9a768ce17e73c61ba7022db927f9ee761830,windows_chrome,61.187.224.*,201,205,2.0,...,280,2,0,5,dc0998c10f8f0b623b5d949e8272e4c7,238,6,d29e59bf0f7f8243858b8183f14d4412,3358,"13866,10057,10006,10063,10110"
4,0,1,18,0899bf144249458ea9c89188473694bf44c7ca15,e4bf79c562745d671b19f2edf7fda89c2e25987f,windows_chrome,117.41.145.*,134,135,2.0,...,200,1,0,5,23485fcd23122d755d38f8c89d46ca56,249,5,7e0e909ea89f707bc20f9585c9072081,3476,"10006,10063,13776,10110"

In [0]:
# list(train_df) # need to remove 'Unnamed: 0', 'urlid', 'bidid','userid'

In [0]:
fh = FeatureHasher(n_features=5, input_type='string')
sp = fh.fit_transform(val_df['useragent'])
sp = pd.DataFrame(sp.toarray(), columns=['useragent1', 'useragent2', 'useragent3', 'useragent4', 'useragent5'])
val_df = pd.concat([val_df, sp], axis=1)

fh = FeatureHasher(n_features=10, input_type='string')
sp = fh.fit_transform(val_df['IP'])
sp = pd.DataFrame(sp.toarray(), columns=['IP1', 'IP2', 'IP3', 'IP4', 'IP5', 'IP6', 'IP7', 'IP8','IP9','IP10'])
val_df = pd.concat([val_df, sp], axis=1)

fh = FeatureHasher(n_features=10, input_type='string')
sp = fh.fit_transform(val_df['domain'].fillna('Unknown'))
sp = pd.DataFrame(sp.toarray(), columns=['domain1', 'domain2', 'domain3', 'domain4', 'domain5', 'domain6', 'domain7', 'domain8','domain9','domain10'])
val_df = pd.concat([val_df, sp], axis=1)

fh = FeatureHasher(n_features=10, input_type='string')
sp = fh.fit_transform(val_df['url'].fillna('Unknown'))
sp = pd.DataFrame(sp.toarray(), columns=['url1', 'url2', 'url3', 'url4', 'url5', 'url6', 'url7', 'url8','url9','url10'])
val_df = pd.concat([val_df, sp], axis=1)

fh = FeatureHasher(n_features=10, input_type='string')
sp = fh.fit_transform(val_df['slotid'])
sp = pd.DataFrame(sp.toarray(), columns=['slotid1', 'slotid2', 'slotid3', 'slotid4', 'slotid5', 'slotid6', 'slotid7', 'slotid8','slotid9','slotid10'])
val_df = pd.concat([val_df, sp], axis=1)

fh = FeatureHasher(n_features=5, input_type='string')
sp = fh.fit_transform(val_df['creative'])
sp = pd.DataFrame(sp.toarray(), columns=['creative1', 'creative2', 'creative3', 'creative4', 'creative5'])
val_df = pd.concat([val_df, sp], axis=1)

fh = FeatureHasher(n_features=3, input_type='string')
sp = fh.fit_transform(val_df['keypage'].fillna('Unknown'))
sp = pd.DataFrame(sp.toarray(), columns=['keypage1', 'keypage2', 'keypage3'])
val_df = pd.concat([val_df, sp], axis=1)

In [0]:
feature_hash = ['useragent','IP','domain','url','slotid','creative','keypage']
val_df = val_df.drop(feature_hash, axis = 1)

In [11]:
cat_vars = ['weekday','region','adexchange','slotvisibility','slotformat','advertiser']

for i in cat_vars:
  one_hot = pd.get_dummies(val_df[i],prefix=i)
  val_df = val_df.drop(i,axis = 1)
  val_df = val_df.join(one_hot)

val_df.head()

,click,hour,bidid,userid,city,urlid,slotwidth,slotheight,slotprice,bidprice,...,slotformat_Na,advertiser_1458,advertiser_2259,advertiser_2261,advertiser_2821,advertiser_2997,advertiser_3358,advertiser_3386,advertiser_3427,advertiser_3476
0,0,20,bbcb813b6166538503d8b33a5602d7d72f6019dc,663169f66491c98c69f1f94a5c48fa34aa9fe06f,79,NaN,160,600,0,300,...,0,1,0,0,0,0,0,0,0,0
1,0,21,5a07316c49477cb5d9b4d5aa39c27d6c3be7f92d,a23f0cfab6592c137f796e68fa752fceba08bb1b,79,NaN,950,90,0,238,...,0,0,0,0,0,0,0,0,0,1
2,0,8,f6ece71dae81d6b16bfb24ad6dd5611472d4c673,5105a013ea54a9706146033e6a138d5234a3803e,2,NaN,300,250,5,238,...,0,0,0,0,0,0,1,0,0,0
3,0,15,b4d5c57c9b38ff5a12954fa01e11931b4e6bfbbb,577e9a768ce17e73c61ba7022db927f9ee761830,205,NaN,336,280,5,238,...,0,0,0,0,0,0,1,0,0,0
4,0,18,0899bf144249458ea9c89188473694bf44c7ca15,e4bf79c562745d671b19f2edf7fda89c2e25987f,135,NaN,200,200,5,249,...,0,0,0,0,0,0,0,0,0,1

In [0]:
# val_df.to_csv(path_or_buf='/content/gdrive/My Drive/we_data/validation_hash2.csv')

In [4]:
train_df = pd.read_csv('/content/gdrive/My Drive/we_data/train_hash2.csv')
train_df.head()

,Unnamed: 0,click,hour,bidid,userid,region,city,urlid,slotwidth,slotheight,...,slotid9,slotid10,creative1,creative2,creative3,creative4,creative5,keypage1,keypage2,keypage3
0,0,0,22,b7bea80521fdecd95d2d761a38c91c3f09618066,2e880fb7d690cf7377b2e42e701728e3f3c0e4c1,2,2,NaN,200,200,...,1.0,-1.0,8.0,3.0,-5.0,4.0,6.0,4.0,2.0,2.0
1,1,0,20,4f51205475678f5a124bc76b2c54163bf8eaa7eb,3a1fe01360ff8100e7d006b83b77a3e4c01d928c,238,239,NaN,300,250,...,2.0,-2.0,0.0,2.0,-1.0,1.0,-1.0,-3.0,-1.0,-1.0
2,2,0,13,b604e3fd054a658ab7ced4285ebf2ef54d2bd890,801d18a056b6fe6b06a794aef17fb0d6daff2414,40,41,NaN,250,250,...,1.0,-1.0,4.0,6.0,-5.0,4.0,3.0,4.0,2.0,2.0
3,3,0,23,0348beeae93e561584c3b50fc9e7746a33048ad7,0d6eaf2259699990e38a1fc5116f112070b9ecdc,1,1,NaN,160,600,...,2.0,-8.0,5.0,2.0,-5.0,6.0,2.0,5.0,7.0,0.0
4,4,0,6,268149c1789bce2bc9798ffd97ec431219bafeb3,a239d9bb642460d974ba67f85e63b8d3e214da0e,216,233,NaN,728,90,...,0.0,-4.0,2.0,0.0,0.0,1.0,-1.0,-3.0,-1.0,-1.0

In [0]:
one_hot = pd.get_dummies(train_df['region'],prefix='region')
train_df = train_df.drop('region',axis = 1)
train_df = train_df.join(one_hot)

In [0]:
for i in range(len(val_df.columns.tolist())):
    if val_df.columns.tolist()[i] not in train_df.columns.tolist():
        print('Variable ' + val_df.columns.tolist()[i] + ' to be added to training set')

In [0]:
for i in range(len(train_df.columns.tolist())):
    if train_df.columns.tolist()[i] not in val_df.columns.tolist():
        print('Variable ' + train_df.columns.tolist()[i] + ' to be added to validation set')

In [0]:
# train_df = train_df.drop('Unnamed: 0',axis=1)
# val_df = val_df.drop('Unnamed: 0',axis=1)

# train_df.to_csv(path_or_buf='/content/gdrive/My Drive/we_data/train_hash2.csv')
# val_df.to_csv(path_or_buf='/content/gdrive/My Drive/we_data/validation_hash2.csv')